spring.application.name=Projeto.Integrador
firebase.project-id=4f2dd
# Informe o caminho do JSON de conta de servico para acesso ao Firebase.
# Exemplo: firebase.credentials-path=C:/credenciais/firebase-service-account.json
firebase.credentials-path=
